name: Translation Check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  check-translations:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Check translations
      run: node scripts/translate-check.js
